### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method markers#update on channel plugins.flutter.io/google_maps_0)

### ISSUE THREAD

**Issue by trushal93** [gauris26/flutter_animarker#39]
E/flutter (13454): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method markers#update on channel plugins.flutter.io/google_maps_0)
E/flutter (13454): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (13454): <asynchronous suspension>
E/flutter (13454): #1      GoogleMapHelper.updateMarkers (package:flutter_animarker/helpers/google_map_helper.dart:8:5)
E/flutter (13454): <asynchronous suspension>
E/flutter (13454): #2      AnimarkerEx.updateMarkers (package:flutter_animarker/widgets/animarker.dart:468:5)
E/flutter (13454): <asynchronous suspension>
E/flutter (13454): #3      AnimarkerState._locationListener (package:flutter_animarker/widgets/animarker.dart:396:5)
E/flutter (13454): <asynchronous suspension>
E/flutter (13454):

**Comment by sindejr** [comment]
Try to use [flutter_animarker 3.3.1-beta.4](https://pub.dev/packages/flutter_animarker/versions/3.3.1-beta.4/example) insted of 3.2.0. 

If you still get the error share your flutter_animarker and GoogleMap implementation code

**Comment by devmfouad** [comment]
any updates about this issue i face same without any solution

**Comment by sagarstackapp** [comment]
@sindejr here is my code snippet. And i used that prelease version but still facing this issue.

```
                 Animarker(
                    shouldAnimateCamera: false,
                    mapId: homeProvider.controller.future.then<int>((value) => value.mapId),
                    runExpressAfter: 0,
                    curve: Curves.linear,
                    markers: {
                      Marker(
                        markerId: const MarkerId('homeProvider.selectedVehicle!.vehicleId!'),
                        position: homeProvider.vehicleLocation!.target,
                        icon: homeProvider.sourceIcon!,
                      ),
                    },
                    child: GoogleMap(
                      mapType: MapType.terrain,
                      initialCameraPosition: homeProvider.vehicleLocation!,
                      polylines: homeProvider.polyline,
                      // markers: {
                      //   Marker(
                      //     markerId: const MarkerId('homeProvider.selectedVehicle!.vehicleId'),
                      //     position: homeProvider.vehicleLocation!.target,
                      //     icon: homeProvider.sourceIcon!,
                      //     rotation: homeProvider.bearing,
                      //   ),
                      // },
                      onMapCreated: (GoogleMapController controller) {
                        if (!homeProvider.controller.isCompleted) {
                          homeProvider.controller.complete(controller);
                        }
                        homeProvider.googleMapController = controller;
                      },
                    ),
                  )
```

Please, provide some better solution on this issue as i am facing this since long time and live is already in play store.

hope, you understand...!

**Comment by sagarstackapp** [comment]
> Try to use [flutter_animarker 3.3.1-beta.4](https://pub.dev/packages/flutter_animarker/versions/3.3.1-beta.4/example) instead of 3.2.0.
> 
> If you still get the error share your flutter_animarker and GoogleMap implementation code

sorry @sindejr but this is not working for me. Can you please refer to my code snippet and help me to sort this issue

**Comment by devmfouad** [comment]
any example please to track driver location like uber using this package

**Comment by sagarstackapp** [comment]
> any example please to track driver location like uber using this package

mention name if you are answering anyone.! @devmfouad
