### ISSUE TITLE
Failed assertion: line 459 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by Hasib74** [gauris26/flutter_animarker#46]

**Comment by binemmanuel** [comment]
I get the same error when the ripple is on, only when it's on.

Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 453 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:453:7)
#3      AnilocationTaskImpl._rippleStatusListener.<anonymous closure> (package:flutter_animarker/infrastructure/anilocation_task_impl.dart:226:44)
#4      new Future.delayed.<anonymous closure> (dart:async/future.dart:427:39)
#5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#7      _Timer._handleMessage (dart:isolate-patch/<…>
